# Generated by Django 5.2.3 on 2025-06-24 09:00

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raids',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raid_id', models.IntegerField(verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Raid')),
                ('reference', models.CharField(db_index=True, max_length=5, verbose_name='Referencia')),
                ('max_attendance', models.IntegerField(default=10, verbose_name='Máximo de jugadores')),
            ],
            options={
                'verbose_name': 'Raid',
                'verbose_name_plural': 'Raids',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.IntegerField(default=0, verbose_name='ID')),
                ('TYPE', models.CharField(blank=True, choices=[('R', 'Raid'), ('P', 'PVP'), ('E', 'Especial')], default='R', max_length=1, null=True, verbose_name='Tipo de Evento')),
                ('reference', models.CharField(db_index=True, max_length=6, verbose_name='Referencia')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción')),
                ('start_time', models.DateTimeField(verbose_name='Inicia')),
                ('lock_at_start_time', models.BooleanField(default=False, verbose_name='Cierra al Iniciar')),
                ('locked', models.BooleanField(default=False, verbose_name='Cerrada')),
                ('reservation_limit', models.IntegerField(default=1, verbose_name='Límite de Reservas')),
                ('allow_comments', models.BooleanField(default=True)),
                ('signups', models.IntegerField(default=0, verbose_name='Anotados')),
                ('raid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.raids')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
