# Generated by Django 5.2.3 on 2025-06-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='TYPE',
        ),
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.CharField(blank=True, choices=[('R', 'Raid'), ('P', 'PVP'), ('E', 'Especial')], default='R', max_length=1, null=True, verbose_name='Tipo de Evento'),
        ),
    ]
