# Generated by Django 5.2.3 on 2025-06-20 05:23

import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialEvents',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('url', models.URLField(blank=True, max_length=250, null=True, verbose_name='Discord URL')),
            ],
            options={
                'verbose_name': 'Evento Especial',
                'verbose_name_plural': 'Eventos Especiales',
            },
        ),
    ]
