# Generated by Django 5.2.3 on 2025-06-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_events_type_events_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['start_time'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
    ]
