# Generated by Django 6.0 on 2026-01-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_events_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='raid_id',
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['start'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.RemoveField(
            model_name='events',
            name='allow_comments',
        ),
        migrations.RemoveField(
            model_name='events',
            name='description',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='events',
            name='lock_at_start_time',
        ),
        migrations.RemoveField(
            model_name='events',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='events',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='events',
            name='reservation_limit',
        ),
        migrations.RemoveField(
            model_name='events',
            name='signups',
        ),
        migrations.RemoveField(
            model_name='events',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='events',
            name='type',
        ),
        migrations.AddField(
            model_name='events',
            name='attendees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='leader',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='start',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Raids',
        ),
    ]
