# Generated by Django 6.0 on 2026-01-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_events_raid_id_alter_events_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
