# Generated by Django 6.0 on 2026-01-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_events_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='discord_channel_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
