# Generated by Django 5.2.3 on 2025-06-24 09:00

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Nombre')),
                ('description', models.CharField(max_length=50, verbose_name='Descripción')),
                ('server', models.CharField(max_length=150, verbose_name='Servidor')),
                ('slogan', models.CharField(max_length=150, verbose_name='Slogan')),
                ('about', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Acerca de')),
                ('active_players', models.IntegerField(default=0, verbose_name='Jugadores Activos')),
                ('actual_progress', models.CharField(max_length=150, verbose_name='Servidor')),
                ('active_years', models.IntegerField(default=0, verbose_name='Años Activos')),
                ('contact', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Contacto')),
                ('discord', models.URLField(verbose_name='URL de discord')),
            ],
            options={
                'verbose_name': 'Información de la Guild',
                'verbose_name_plural': 'Informaciones de la Guild',
            },
        ),
        migrations.CreateModel(
            name='LootSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rules', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Reglas de Loot')),
                ('council', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Loot Council')),
            ],
            options={
                'verbose_name': 'Sistema de Loot',
                'verbose_name_plural': 'Sistemas de Loot',
            },
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cta', models.CharField(db_index=True, max_length=150, verbose_name='CTA')),
                ('requirements', models.CharField(max_length=150, verbose_name='Requisitos')),
            ],
            options={
                'verbose_name': 'Requerimiento',
                'verbose_name_plural': 'Requerimientos',
            },
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('honor', models.CharField(max_length=250, verbose_name='Código de Honor')),
                ('commitment', models.CharField(max_length=250, verbose_name='Compromiso')),
                ('communication', models.CharField(max_length=250, verbose_name='Comunicación')),
                ('loot', models.CharField(max_length=250, verbose_name='Botín')),
            ],
            options={
                'verbose_name': 'Regla',
                'verbose_name_plural': 'Reglas',
            },
        ),
        migrations.CreateModel(
            name='WoWClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Clase')),
                ('priority', models.CharField(blank=True, choices=[('H', 'Alta'), ('M', 'Media'), ('L', 'Baja')], default='L', max_length=1, null=True, verbose_name='Prioridad')),
                ('recruitment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='guild.recruitment')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
            },
        ),
    ]
