# Generated by Django 5.2.3 on 2025-06-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='media/uploads/images/', width_field='image_width'),
        ),
        migrations.AddField(
            model_name='guild',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='guild',
            name='image_ppoi',
            field=models.CharField(default='0.5x0.5', max_length=20),
        ),
        migrations.AddField(
            model_name='guild',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='guild',
            name='actual_progress',
            field=models.CharField(max_length=150, verbose_name='Progreso Actual'),
        ),
    ]
