# Generated by Django 5.2.3 on 2025-06-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0002_guild_image_guild_image_height_guild_image_ppoi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', upload_to='media/uploads/images/', width_field='image_width'),
        ),
    ]
