# Generated by Django 5.2.3 on 2025-06-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0003_alter_guild_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitment',
            options={'verbose_name': 'Reclutamiento', 'verbose_name_plural': 'Reclutamientos'},
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='cta',
        ),
    ]
