# Generated by Django 5.2.3 on 2025-06-24 18:14

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0004_alter_recruitment_options_remove_recruitment_cta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wowclass',
            options={'ordering': ['name'], 'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
        migrations.AlterField(
            model_name='rules',
            name='commitment',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=250, verbose_name='Compromiso'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='communication',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=250, verbose_name='Comunicación'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='honor',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=250, verbose_name='Código de Honor'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='loot',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=250, verbose_name='Botín'),
        ),
    ]
