# Generated by Django 5.2.3 on 2025-06-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0005_alter_wowclass_options_alter_rules_commitment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lootsystem',
            name='council',
        ),
    ]
