# Generated by Django 5.2.3 on 2025-06-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0006_remove_lootsystem_council'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='raid_times',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Horarios de Raid'),
        ),
    ]
