# Generated by Django 5.2.3 on 2025-06-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0007_guild_raid_times'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guild',
            options={'verbose_name': 'Info de la Guild', 'verbose_name_plural': 'Info de la Guild'},
        ),
        migrations.AlterModelOptions(
            name='lootsystem',
            options={'verbose_name': 'Sistema de Loot', 'verbose_name_plural': 'Sistema de Loot'},
        ),
        migrations.AlterModelOptions(
            name='recruitment',
            options={'verbose_name': 'Reclutamiento', 'verbose_name_plural': 'Reclutamiento'},
        ),
    ]
