# Generated by Django 5.2.3 on 2025-06-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0008_alter_guild_options_alter_lootsystem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guild',
            options={'verbose_name': 'Info del Gremio', 'verbose_name_plural': 'Info del Gremio'},
        ),
        migrations.RemoveField(
            model_name='guild',
            name='active_years',
        ),
        migrations.AddField(
            model_name='guild',
            name='founded',
            field=models.DateField(blank=True, null=True, verbose_name='Fundada'),
        ),
        migrations.AddField(
            model_name='guild',
            name='tags',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Etiquetas'),
        ),
    ]
