# Generated by Django 5.2.3 on 2025-07-08 06:17

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0009_alter_guild_options_remove_guild_active_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='commitment',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Compromiso'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='communication',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Comunicación'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='honor',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Código de Honor'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='loot',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Botín'),
        ),
    ]
