# Generated by Django 5.2.3 on 2025-06-19 10:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slogan', models.CharField(max_length=55, verbose_name='Slogan')),
            ],
            options={
                'verbose_name': 'Quién Somos',
                'verbose_name_plural': 'Quiénes Somos',
            },
        ),
        migrations.CreateModel(
            name='AboutUsCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, verbose_name='Títulp')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='landing.aboutus')),
            ],
            options={
                'verbose_name': 'Card Sección Quien Somos',
                'verbose_name_plural': 'Card Sección Quien Somos',
            },
        ),
    ]
