# Generated by Django 5.2.3 on 2025-06-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='slogan',
            field=models.CharField(max_length=75, verbose_name='Slogan'),
        ),
    ]
