# Generated by Django 5.2.3 on 2025-06-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='media/uploads/images/', width_field='image_width'),
        ),
    ]
