# Generated by Django 5.2.3 on 2025-06-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_aboutus_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuscard',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Título'),
        ),
    ]
