# Generated by Django 5.2.3 on 2025-06-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_remove_galleryimage_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='description',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nombre de la Galería de Imágenes'),
        ),
    ]
