# Generated by Django 5.2.3 on 2025-06-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_gallery_galleryimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Galería de Imagen', 'verbose_name_plural': 'Galería de Imágenes'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': 'Imagen', 'verbose_name_plural': 'Imágenes'},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre'),
        ),
    ]
